parameters:
  query_cache: true
services:
  Aazsamir\LibphpskySymfony\ATProtoClientFactory:
    arguments:
      $cache: "@cache.app"
      $useQueryCache: "%query_cache%"

  Aazsamir\LibphpskySymfony\ATProtoMetaClientFactory:
    arguments:
      - '@Aazsamir\Libphpsky\Client\ATProtoClientInterface'

  Aazsamir\Libphpsky\Client\ATProtoClientInterface:
    factory: ['@Aazsamir\LibphpskySymfony\ATProtoClientFactory', "create"]

  Aazsamir\Libphpsky\Model\Meta\ATProtoMetaClient:
    factory: ['@Aazsamir\LibphpskySymfony\ATProtoMetaClientFactory', "create"]

  Aazsamir\Libphpsky\Model\:
        resource: '../../../../libphpsky/src/Model/*'
        exclude: '../{\ATProtoMetaClient.php}'
        autowire: true
        autoconfigure: true
